### PR TITLE
fix: fix #126, #146, #147 and #159

### LINKED ISSUE #126: Aliaslist bugs
- title not shown in full
- invalid values displayed as well
`<meta http-equiv="refresh" content="0; URL='http://example.org'" /> ⟶ aliaslist`

<hr><sub>[original: febee99/ped#5]<br/>
</sub>

### LINKED ISSUE #146: Confusing line in Alias list
Without adding any new aliases, there is a confusing line of code in the aliaslist window.

<hr><sub>[original: czkay/ped#11]<br/>
</sub>

### LINKED ISSUE #147: Improper example command in UG
Typing the example command from the UG below into VISIT will actually give an error.

<hr><sub>[original: czkay/ped#12]<br/>
</sub>

### LINKED ISSUE #159: Alias small bug for edge case
Adding an alias for unalias does not allow me to use it to unalias itself.

<hr><sub>[original: jeunhoe/ped#11]<br/>
</sub>

### PR DESCRIPTION
**Pull request by Wingedevil**
Closes #126, closes #146, closes #147 and closes #159

### CODE REVIEW

File: src/main/java/seedu/address/model/AliasTable.java [hunk 1]
```diff
@@ -18,8 +18,7 @@ public static AliasTable getDefaultAliasTable() {
         AliasTable rtv = new AliasTable();
         rtv.addAlias("h", "help")
                 .addAlias("a", "add")
-                .addAlias("e", "exit")
-                .addAlias("<meta http-equiv=\"refresh\" content=\"0; URL='http://example.org'\" />", "aliaslist");
```
Comment (Q-gabe) [inline src/main/java/seedu/address/model/AliasTable.java]: 😢
